import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import crypto from 'node:crypto';
import {preset,simulate,Session,contacts,rhs,drive,geometry,quaternion,validate,toCSV} from '../web/src/walking.js';
const fixture=JSON.parse(fs.readFileSync(new URL('./walking-reference.json',import.meta.url)));
test('reference is bound to the published independent Python solver',()=>assert.equal(crypto.createHash('sha256').update(fs.readFileSync(new URL('../python/walking_model.py',import.meta.url))).digest('hex'),fixture.python_model_sha256));
for(const row of fixture.cases)test(`walking Python parity: ${row.name} / ${row.mode}`,()=>{
 const c=preset(row.name);c.mode=row.mode;c.numerics=row.config.numerics;assert.deepEqual(c,row.config);const r=simulate(c);
 for(const ref of row.samples){const got=r.samples[ref.index];for(const key of ['state','force','support','quaternion'])for(let j=0;j<ref[key].length;j++)assert.ok(Math.abs(got[key][j]-ref[key][j])<2e-7,`${row.name}/${row.mode} ${key}[${j}] at ${ref.t}`);assert.ok(Math.abs(got.residual-ref.residual)<2e-7);}
 for(const [key,pythonKey] of [['heaveRmsMm','heave_rms_mm'],['rollRmsDeg','roll_rms_deg'],['pitchRmsDeg','pitch_rms_deg'],['peakForceN','peak_patch_N'],['contactLossFraction','zero_force_fraction'],['anyContactLossFraction','any_zero_force_fraction']])assert.ok(Math.abs(r.stats[key]-row.stats[pythonKey])<2e-7,`${key}: ${r.stats[key]} vs ${row.stats[pythonKey]}`);
 assert.ok(Math.abs(r.stats.peakSideN-row.stats.peak_side_over_static*2*r.derived.staticForce)<2e-7);
});
test('live chunks and batch have identical trajectories and statistics, independent of render timing',()=>{const c=preset('Gvar');c.numerics.duration_s=12;const batch=simulate(c),session=new Session(c);for(const target of [.013,.177,.29,1.83,2.004,5.91,5,7.12,12])session.advanceTo(target);assert.deepEqual(session.result(),batch);});
test('force statistics use every integration step, independent of exported sample interval',()=>{const c=preset('Gstress');c.numerics.duration_s=12;const a=simulate(c);c.numerics.sample_dt_s=.05;const b=simulate(c);for(const key of ['peakForceN','peakSideN','contactLossFraction','forceSampleCount'])assert.equal(a.stats[key],b.stats[key]);assert.ok(a.stats.forceSampleCount>b.stats.sampleCount);});
test('no reported analysis before its window, and live output is a bounded prefix',()=>{const s=new Session(preset());s.advanceTo(.13);assert.equal(s.samples.at(-1).t,.13);assert.equal(s.stats.heaveRmsMm,null);assert.equal(s.stats.peakForceN,null);assert.equal(s.result().complete,false);});
test('120-second walking run is continuous and CSV has aligned physical columns',()=>{const r=simulate(preset());assert.equal(r.samples.length,12001);assert.equal(r.samples.at(-1).t,120);assert.ok(r.stats.maxEnergyResidualJ<1e-5);const lines=toCSV(r).trim().split('\n'),head=lines[0].split(',');assert.equal(lines.length,12002);assert.equal(head.length,lines.at(-1).split(',').length);assert.equal(lines.at(-1).split(',')[0],'120');assert.ok(head.includes('pitch_deg'));assert.ok(head.includes('front_left_force_N'));});
test('collapsed CSV explicitly labels allocated patch values',()=>{const c=preset('G180');c.mode='collapsed';c.numerics.duration_s=9;const r=simulate(c),header=toCSV(r).split('\n')[0];assert.match(header,/allocated_front_left_force_N/);assert.ok(r.samples.every(s=>s.pitch===0&&s.force[0]===s.force[2]&&s.force[1]===s.force[3]));});
test('cadence, phase, geometry and initial pitch change solved response',()=>{const c=preset();c.numerics.duration_s=9;const baseline=simulate(c);for(const edit of [x=>x.gait.step_hz[1]=2.15,x=>x.gait.stride_phase_rad[1]=0,x=>x.parameters.half_length=.9,x=>x.initial.pitch_rad=.02]){const b=structuredClone(c);edit(b);const r=simulate(b);assert.ok(r.samples.some((s,i)=>Math.abs(s.pitch-baseline.samples[i].pitch)>1e-4));}});
test('geometry and quaternion match independent rotation matrix; forces do virtual work',()=>{const c=preset(),p=c.parameters,y=[1.51,.24,-.18,.1,.02,-.03,0,0],geo=geometry(y,p),q=quaternion(y[1],y[2]);assert.ok(Math.abs(Math.hypot(...q)-1)<1e-14);for(let i=0;i<4;i++){const x=i<2?p.half_length:-p.half_length,side=i%2?p.half_width:-p.half_width,cy=Math.cos(y[1]),sy=Math.sin(y[1]),ct=Math.cos(y[2]),st=Math.sin(y[2]);const expected=[ct*x+st*(sy*side-cy*p.com_height),cy*side+sy*p.com_height,y[0]-st*x+ct*(sy*side-cy*p.com_height)];for(let j=0;j<3;j++)assert.ok(Math.abs(geo.points[i][j]-expected[j])<1e-14);for(let j=0;j<3;j++){const plus=[...y],minus=[...y];plus[j]+=1e-6;minus[j]-=1e-6;assert.ok(Math.abs((geometry(plus,p).points[i][2]-geometry(minus,p).points[i][2])/2e-6-geo.jacobian[i][j])<3e-10);}}});
test('support velocity differentiates ramped and modulated heights',()=>{const c=preset('Gvar');for(const t of [.4,1.3,3.13,8.71]){const a=drive(t-1e-6,c.parameters,c.gait),b=drive(t+1e-6,c.parameters,c.gait),d=drive(t,c.parameters,c.gait);for(let i=0;i<4;i++)assert.ok(Math.abs((b.support[i]-a.support[i])/2e-6-d.velocity[i])<1e-9);}});
test('zero drive equilibrium and non-tensile contacts',()=>{const c=preset();c.gait.vertical_m=[0,0];c.gait.tilt_rad=[0,0];const y=[c.parameters.z0,0,0,0,0,0,0,0];assert.ok(rhs(0,y,c).every(v=>Math.abs(v)<1e-9));y[0]+=.2;assert.deepEqual(contacts(0,y,c).force,[0,0,0,0]);});
test('walking rejects malformed, unstable, aliased and excessive configurations',()=>{for(const edit of [c=>c.parameters.mass=NaN,c=>c.parameters.half_width=.001,c=>c.parameters.inertia_yaw=100,c=>c.gait.step_hz=[2],c=>c.gait.step_hz[0]=0,c=>c.gait.phase_mod_rad=[10,10],c=>c.gait.vertical_m[0]=.101,c=>c.numerics.dt_s=0,c=>c.numerics.sample_dt_s=.0105,c=>c.numerics.analysis_start_s=120,c=>c.initial.pitch_rad=1,c=>{c.mode='pitch_locked';c.initial.pitch_rad=.01;},c=>{c.numerics.dt_s=.00005;c.numerics.duration_s=180;}]){const c=preset();edit(c);assert.throws(()=>validate(c));}});
